### ISSUE TITLE
Not all routes mapped after deployment with legacy-push

### ISSUE THREAD

**Issue by seinol** [HappyTobi/cf-puppeteer#19]
Since release v1.2.0, a `zero-downtime-push --legacy-push` no longer binds all routes to the new deployed app.

**Example scenario:**
    routes:
      - route: my-app.example.com
      - route: my-app.sub.example.com
      - route: my-app-2.sub.example.com
Results in a newly deployed app with only the last two routes(routes with sub) assigned to the app.

**Comment by HappyTobi** [comment]
Hi @seinol,

i tied it again but i couldn't reproduce the issue.
Can you provide some log informations please?

The important part begin with the: 
`check if routes should be added or switched from existing one` log output

Kind regards

**Comment by HappyTobi** [comment]
Hi @seinol,

The issue was fixed in the latest build.
Can you verify that?

https://github.com/HappyTobi/cf-puppeteer/actions/runs/67715681

Kind regards

**Comment by r-chris** [comment]
I've also seen issues with the route matching / mapping. How can I try the latest version?

**Comment by r-chris** [comment]
Ok, so I tried the (linux) version you linked and for me I'm still seeing issues with the routes. An example:

The initial app has these routes assigned:

```
routes:
    - route: staging-p.cfapp.io
    - route: staging-product.cfapp.io
    - route: staging.product.com
```

During the deployment the log shows this:

```
check if routes should be added or switched from existing one
map routes to new application product-staging
map route [map-route product-staging cfapp.io --hostname staging-p]map route [map-route product-staging cfapp.io --hostname staging-product]Deleting app product-staging-venerable in org Product / space Staging as ***...
```

Note that the (reasonably important) route: ` staging.product.com` appears to be missing here.

The newly deployed app now only has these routes:
```
routes:
    - route: staging-p.cfapp.io
    - route: staging-product.cfapp.io
```

**Comment by HappyTobi** [comment]
Hi @r-chris,

Thx for the response!

Is the route entity listing on when you run the following command? `cf curl /v2/domains`

Or is the domain part of your org?
`cf curl /v2/organizations/<oid>/private_domains `?

See the doc also
https://apidocs.cloudfoundry.org/12.41.0/organizations/list_all_private_domains_for_the_organization.html

In the /v3/domains call are all entries (private and „normal“ ones)

Kind regards

**Comment by r-chris** [comment]
> Is the route entity listing on when you run the following command? `cf curl /v2/domains`

I get a (json) "list" of 30 entries when running that command and - the all the relevant domains are listed here as `"entity"`.

> Or is the domain part of your org?
> `cf curl /v2/organizations/<oid>/private_domains `?

I get a list of 25 `"entity"` entries here - all of which were also contained in the response of the previous `cf curl` request.

> See the doc also
> https://apidocs.cloudfoundry.org/12.41.0/organizations/list_all_private_domains_for_the_organization.html
> 
> In the /v3/domains call are all entries (private and „normal“ ones)

Here, I get 30 results with 29 of them having this flag: `"internal": false,` - again all of the relevant domains are listed.

**Comment by r-chris** [comment]
PS: thanks for your help here, it's very much appreciated

**Comment by HappyTobi** [comment]
@r-chris 

does the entities look like that for the `/v2/domains` call?

```json
"entity": {
  "name": "product.com",
  "internal": false,
 ...
},
"entity": {
  "name": "cfapp.io",
  "internal": false,
 ...
}
```

Because I have the Problem that I can't reproduce the problem in my test.

Kind regards

**Comment by HappyTobi** [comment]
Hi @r-chris and @seinol,

can you try the latest build and run them with the `CF_TRACE=true` or `CF_TRAGE=/dev/stdout`
https://github.com/HappyTobi/cf-puppeteer/actions/runs/85478592

Hope to get more inside of the problem. (There are special debug logs than).

Kind regards
Tobi

**Comment by r-chris** [comment]
> does the entities look like that for the /v2/domains call?

yes, pretty much like that, but the ones making trouble usually have sub-domains as well:

```
"entity": {
  "name": "staging-api.product.com",
  "internal": false,
 ...
},
"entity": {
  "name": "dev-api.product.com",
  "internal": false,
 ...
},
"entity": {
  "name": "api.product.com",
  "internal": false,
 ...
},
"entity": {
  "name": "staging.product.com",
  "internal": false,
 ...
},
"entity": {
  "name": "www.product.com",
  "internal": false,
 ...
},
"entity": {
  "name": "apps.internal",
  "internal": true,
 ...
},
"entity": {
  "name": "cfapp.io",
  "internal": false,
 ...
}
```

My intuition was that there is something wrong with matching these domains (maybe there is some regex or other domain matching at play here somewhere that doesn't work well on sub-domains?).

That assumption stems from the observation that I have also see weird domains being assigned that shouldn't even exist. I can't find an exact example right this moment, but the mangled up route looked something like this:

`staging-.api.product.com` when it should have been `staging-api.product.com`

**Comment by r-chris** [comment]
> can you try the latest build and run them with

I'll take a look as soon as I can - thanks for trying to solve this for us!

**Comment by HappyTobi** [comment]
Hi @r-chris,

thx I will update my test with your example above and try to find the issue.

Kind regards.
Tobi

**Comment by HappyTobi** [comment]
Hi @r-chris and @seinol ,

can you try the latest build? I fix the issue, empty Hostnames are allowed now.

Dl link to the build.
https://github.com/HappyTobi/cf-puppeteer/actions/runs/89491274

Can you tell me if that fix your issue?

Kind regards
Tobi

**Comment by r-chris** [comment]
Hi @HappyTobi I couldn't test it, yet, but I'll try to get to it today

**Comment by r-chris** [comment]
Hello again @HappyTobi - I tested this today and couldn't reproduce the issues I have seen with the release you linked. Thank and great work! Grüsse nach Stuttgart!

**Comment by seinol** [comment]
Hi @HappyTobi 
It also works in our case. Thank you for your great support! 
Grüsse aus der Schweiz

**Comment by HappyTobi** [comment]
I will create a new Release and create a PR for update the Plugin in the CF Plugin repo
